version: "4"

x-kong-config: &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-off}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: kong-db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
  KONG_PASSWORD: kong

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  marine:
    external: true

services:
  db:
    image: postgres:16.1
    container_name: kong-db
    networks:
      - marine
    restart: on-failure
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
  kong-migrations:
    image: kong/kong-gateway:3.5.0.1
    container_name: kong-migrations
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - marine
  kong:
    image: kong/kong-gateway:3.5.0.1
    container_name: kong-gateway
    restart: on-failure
    depends_on:
      - kong-migrations
    networks:
      - marine
    secrets:
      - kong_postgres_password
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:3001
    ports:
      - 3000:8000
      - 3001:3001
  konga:
    image: pantsel/konga:next
    container_name: konga
    restart: on-failure
    depends_on:
      - kong
    networks:
      - marine
    ports:
      - 1337:1337
    environment:
      TOKEN_SECRET: 1982dn918n2d981n29d898fb813f08b130f8b3
  
secrets:
  kong_postgres_password:
    file: ./POSTGRES_PASSWORD
